/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/SpinTextLocal copy.vue')['default']
    Fonts: typeof import('./src/components/Fonts.vue')['default']
    LenisScroll: typeof import('./src/components/scroll/LenisScroll.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NavigationContact: typeof import('./src/components/NavigationContact.vue')['default']
    NavigationPanel: typeof import('./src/components/NavigationPanel.vue')['default']
    NavigationSection: typeof import('./src/components/NavigationSection.vue')['default']
    NavigationSocials: typeof import('./src/components/NavigationSocials.vue')['default']
    ParallaxPicture: typeof import('./src/components/scroll/ParallaxPicture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinText: typeof import('./src/components/SpinText.vue')['default']
    SpinTextExternal: typeof import('./src/components/SpinTextExternal.vue')['default']
    SpinTextInternal: typeof import('./src/components/SpinTextInternal.vue')['default']
    SpinTextLocal: typeof import('./src/components/SpinTextLocal.vue')['default']
    VideoScrollSync: typeof import('./src/components/scroll/VideoScrollSync.vue')['default']
  }
}
