/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    AdjacentIcon: typeof import('./src/components/AdjacentIcon.vue')['default']
    Background: typeof import('./src/components/cursor/Background.vue')['default']
    Cursor: typeof import('./src/components/cursor/Cursor.vue')['default']
    DrawPath: typeof import('./src/components/effects/DrawPath.vue')['default']
    EducationSection: typeof import('./src/components/EducationSection.vue')['default']
    FocusCard: typeof import('./src/components/cursor/FocusCard.vue')['default']
    Fonts: typeof import('./src/components/Fonts.vue')['default']
    FullScreenableMedia: typeof import('./src/components/cursor/FullScreenableMedia.vue')['default']
    HorizontalSticky: typeof import('./src/components/scroll/HorizontalSticky.vue')['default']
    InterestsSection: typeof import('./src/components/InterestsSection.vue')['default']
    LandingSection: typeof import('./src/components/LandingSection.vue')['default']
    LenisScroll: typeof import('./src/components/scroll/LenisScroll.vue')['default']
    LocationSection: typeof import('./src/components/LocationSection.vue')['default']
    NavigationBar: typeof import('./src/components/navigation/NavigationBar.vue')['default']
    NavigationContact: typeof import('./src/components/navigation/NavigationContact.vue')['default']
    NavigationPanel: typeof import('./src/components/navigation/NavigationPanel.vue')['default']
    NavigationSocials: typeof import('./src/components/navigation/NavigationSocials.vue')['default']
    OpaqueButton: typeof import('./src/components/OpaqueButton.vue')['default']
    ParallaxContent: typeof import('./src/components/scroll/ParallaxContent.vue')['default']
    ProjectDemonstration: typeof import('./src/components/ProjectDemonstration.vue')['default']
    ProjectSection: typeof import('./src/components/ProjectSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollText: typeof import('./src/components/effects/ScrollText.vue')['default']
    SimpleModelRender: typeof import('./src/components/3d/SimpleModelRender.vue')['default']
    SpinTextExternal: typeof import('./src/components/SpinTextExternal.vue')['default']
    SpinTextInternal: typeof import('./src/components/SpinTextInternal.vue')['default']
    TiledComponent: typeof import('./src/components/TiledComponent.vue')['default']
    TimelineComponent: typeof import('./src/components/TimelineComponent.vue')['default']
    TransparentButton: typeof import('./src/components/TransparentButton.vue')['default']
    VideoScrollSync: typeof import('./src/components/scroll/VideoScrollSync.vue')['default']
  }
}
